PRM/MainApplication/PUCIT.AIMRL.PRM.MainApp/Controllers/PartialController.cs
using PUCIT.AIMRL.PRM.MainApp.Util;
using PUCIT.AIMRL.PRM.UI.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PUCIT.AIMRL.PRM.MainApp.Controllers
{
    public class PartialController : BaseController
    {
        public ActionResult YesNoModal()
        {
            return PartialView();
        }

    }
}

PRM/MainApplication/PUCIT.AIMRL.PRM.MainApp/Controllers/SecurityController.cs
using PUCIT.AIMRL.PRM.MainApp.Util;
using PUCIT.AIMRL.PRM.UI.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PUCIT.AIMRL.PRM.MainApp.Controllers
{
    public class SecurityController : BaseController
    {
        //
        // GET: /Admin/
        public ActionResult Index()
        {
            if (PUCIT.AIMRL.PRM.MainApp.Security.PermissionManager.perManageSecurityUsers == false
                && PUCIT.AIMRL.PRM.MainApp.Security.PermissionManager.perManageSecurityRoles == false
                && PUCIT.AIMRL.PRM.MainApp.Security.PermissionManager.perManageSecurityPermissions == false)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }
        public ActionResult AddUserbulk()
        {
            if (PUCIT.AIMRL.PRM.MainApp.Security.PermissionManager.perManageSecurityUsers == false)  {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }
        public ActionResult Users()
        {
            if (PUCIT.AIMRL.PRM.MainApp.Security.PermissionManager.perManageSecurityUsers== false)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }
        public ActionResult Roles()
        {
            if (PUCIT.AIMRL.PRM.MainApp.Security.PermissionManager.perManageSecurityRoles == false)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Id = 1;
                return View();
            }
        }
        public ActionResult Permissions()
        {
            if (PUCIT.AIMRL.PRM.MainApp.Security.PermissionManager.perManageSecurityPermissions == false)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Id = 2;
                return View();
            }
        }
        public ActionResult GoogleUsers()
        {
            if (PUCIT.AIMRL.PRM.MainApp.Security.PermissionManager.perManageSecurityUsers == false)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }
        public ActionResult AddNewItems()
        {
            return View();
        }

    }
}

PRM/MainApplication/PUCIT.AIMRL.PRM.MainApp/Views/Security/AddNewItems.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Header
{
    <script type="text/javascript" src="@Url.Content("~/Scripts/mywebapp/Security/mywebapp.ui.addNewItems.js")"></script>
    @Scripts.Render("~/bundles/roles")
}
@section scripts
{
    <script type="text/javascript">

        $(document).ready(function () {
            debugger;
            MyWebApp.UI.AddNewItems.readyMain();
        });
    </script>
}
@section BreadCrumb
{
    <li>
        <a href='@Url.Content("~/Security/")'>Security</a>
    </li>
    <li>
        <a href='@Url.Content("~/Security/AddNewItems/")'>Add New Items</a>
    </li>
}


<div class="page-content">
    <div class="page-header">
        <h1>
            Add New Items:
            <select style="display:inline ; font-size:small" id="selectType1">
                <option value="-1">All</option>
                <option value="1">Active</option>
                <option value="0">In Active</option>
            </select>
            <a role="button" class="btn-new-mail pull-right" data-toggle="modal" id="newItem">
                <span class="btn btn-purple no-border">
                    <i class="menu-icon fa fa-pencil-square-o"></i>
                    <span class="bigger-110">Add new Items</span>
                </span>
            </a>
        </h1>
    </div><!-- /.page-header -->
    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="row">
                <div class="col-xs-12">
                    <div class="message-list-container">
                        <div class="message-list" id="Roles">
                            <table id="simple-table-Item" class="table  table-bordered table-hover"></table>
                        </div>
                    </div>
                </div>
            </div><!-- /.row -->
            <!-- /.modal-content -->
        </div>
    </div><!-- PAGE CONTENT ENDS -->
</div>



@section PopupsAndTemplates
{
    @{
        Html.RenderAction("YesNoModal", "Partial");
    }
    <div id="modal-form" tabindex="-1" class="modal" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" id="ModalClose" class="close" data-dismiss="modal">×</button>
                    <h4 class="blue bigger">Item information</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div style="padding-left:50px;">
                            <input type="hidden" name="hiddenid" id="hiddenid" />
                            <div class="col-xs-5">
                                <label class="asterisk" for="form-field-first"><b>Name : </b></label>
                                <input type="text" class="input-sm form-control" id="Itemname" />
                            </div>
                        </div>
                        <div style="padding-left:50px;">
                            <div class="col-xs-5">
                                <label class="asterisk" for="form-field-first"><b> Fund Description : </b></label>
                                <input type="text" class="input-sm form-control" id="ItemDescription" />
                            </div>
                        </div>
                        <div id="item_category"></div>
                        <div style="padding-left:50px;">
                            <label class="asterisk" for="form-field-first"><b> Please select category: </b></label>
                        </div>

                        <div style="padding-left:50px;">
                            <div class="col-xs-5">
                                <input type="radio" id="generalItem" name="option" value="1" />
                                <label for="form-field-signature"><b> General Item  </b> </label>
                            </div>
                            <div class="col-xs-5">
                                <input type="radio" id="hardwareItem" name="option" value="2" />
                                <label for="form-field-signature"><b> Hardware Item  </b> </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-sm" data-dismiss="modal" id="Cancel">
                        <i class="ace-icon fa fa-times"></i>
                        Cancel
                    </button>
                    <button class="btn btn-sm btn-primary" id="Save">
                        <i class="ace-icon fa fa-check"></i>
                        Save
                    </button>
                </div>
            </div>
        </div>
    </div>


    <div id="modal-form-qty" tabindex="-1" class="modal" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" id="ModalClose1" class="close" data-dismiss="modal">×</button>
                    <h4 class="blue bigger">Item information</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div style="padding-left:50px;">
                            <input type="hidden" name="hiddenidQty" id="hiddenidQty" />
                            <div class="col-xs-5">
                                <label class="asterisk" for="form-field-first"><b>Name : </b></label>
                                <input type="text" class="input-sm form-control" id="ItemnameQty" readonly="readonly" />
                            </div>
                        </div>
                        <div style="padding-left:50px;">
                            <div class="col-xs-5">
                                <label class="asterisk" for="form-field-first"><b>Quantity : </b></label>
                                <input type="text" class="input-sm form-control" id="ItemQuantity" readonly="readonly" />
                            </div>
                        </div>
                        <br>
                        <div style="padding-left:50px;">
                            <div class="col-xs-5">
                                <label class="asterisk" for="form-field-first"><b>Incoming Quantity : </b></label>
                                <input type="text" class="input-sm form-control" id="ItemInQuantity" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-sm" data-dismiss="modal" id="Cancel1">
                        <i class="ace-icon fa fa-times"></i>
                        Cancel
                    </button>
                    <button class="btn btn-sm btn-primary" id="SaveQty">
                        <i class="ace-icon fa fa-check"></i>
                        Save
                    </button>
                </div>
            </div>
        </div>
    </div>



    <div id="EditPermissionsModal" tabindex="-1" class="modal" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" id="closeedit" class="close" data-dismiss="modal">×</button>
                    <h4 class="primary bigger">Permissions Assignment</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-12 col-sm-11">
                            <div class="space-4"></div>
                            <div class="row">
                                <div id="draggable" style="max-height:250px;overflow-y:auto">
                                    <ol id="sortable1" style="list-style-type:none"></ol>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-sm" data-dismiss="modal" id="CancelPermModal">
                        <i class="ace-icon fa fa-times"></i>
                        Cancel
                    </button>
                    <button class="btn btn-sm btn-primary" id="SaveMappings">
                        <i class="ace-icon fa fa-check"></i>
                        Save
                    </button>
                </div>
            </div>
        </div>
    </div>
    <script id="RoleTemplate" type="text/x-handlebars-template">
        <thead>
            <tr id="#">
                <th>Name</th>
                <th>Description</th>
                <th>Quantity</th>

                <th scope="col" width="5%">Edit</th>
                <th scope="col" width="5%">Manage Quantity</th>
                <th scope="col" width="5%">Enable/Disable</th>
            </tr>
        </thead>
        <tbody>
            {{#each ItemsList}}
            <tr id="{{ItemId}}">
                <td>
                    <a href="#">{{ItemName}}</a>
                </td>
                <td>{{Description}}</td>
                <td>{{Quantity}}</td>
                <td align="center">
                    <div class="tblActions">
                        <a role="button" data-toggle="modal" class="edit btn-xs btn-new-mail  btn btn-purple no-border lnkEditItem" title="Click to edit">
                            <i class="menu-icon fa fa-pencil-square-o"></i>
                            <span class="bigger-110"></span>
                        </a>
                    </div>
                </td>
                <td align="center">
                    <div class="tblActions" id="manageQty">
                        <a role="button" data-toggle="modal" class="edit btn-xs btn-new-mail  btn btn-purple no-border lnkQtyItem" title="Click to Manage Quantity">
                            <i class="menu-icon fa fa-pencil-square-o"></i>
                            <span class="bigger-110"></span>
                        </a>
                    </div>
                </td>
                <td align="center" align="middle">
                    <div class="tblActions">
                        {{#ifEqual IsActive false}}
                        <a href="#" class="btn btn-xs btn-round widget-color-green lnkDeleteItem" id="dltbtn" title="Click to activate">
                            <i class="ace-icon icon-off"></i>
                        </a>
                        {{/ifEqual}}
                        {{#ifEqual IsActive true}}
                        <a href="#" class="delete btn btn-xs btn-danger btn-round lnkDeleteItem" id="dltbtn" title="Click to deactivate">
                            <i class="ace-icon icon-off"></i>
                        </a>
                        {{/ifEqual }}
                    </div>
                </td>
            </tr>
            {{/each}}
        </tbody>
    </script>

}

PRM/MainApplication/PUCIT.AIMRL.PRM.MainApp/Views/Security/AddUserBulk.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Header
{
    @*<script type="text/javascript" src="@Url.Content("~/Scripts/mywebapp/Security/mywebapp.ui.bulkloading.js")"></script>*@
       @Scripts.Render("~/bundles/usersbulk")
}
@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            MyWebApp.UI.Security.UserBulk.readyMain();
        });
    </script>
}
@section BreadCrumb
{
    <li>
        <a href='@Url.Content("~/Security/")'>Security</a>
    </li>
    <li>
        <a href='@Url.Content("~/Security/AddUserBulk/")'>Add Users Bulk</a>
    </li>
}

<div class="page-content">  
    <div class="row pull-right">
           <div class="col-xs-12 col-sm-12" >
                <span class="blue">  <i class="ace-icon fa fa-download"></i> <a href='@Url.Content("~/Sample_Data/Sample_CSV _File.csv")'> <b>Sample CSV file  </b></a></span>         
              </div>
           </div>
    <div class="row pull pull-left">
        <div style="padding-left: 50px;">
            <div class="col-md-3">
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <div id="attach_result_ID"></div>
                
                      <label  for="form-field-username"><b>Upload_Students_Data_File</b></label>
                      <input type="file" id="datafile" />
                            <div class="space"></div>
                            <button id="uploadfile" class="btn btn-sm btn-primary">
                                <i class="ace-icon fa fa-upload"></i>
                                Upload
                            </button>
                </div>
            </div>
            
             </div>
            <div class="col-md-3">
            </div>

        </div>
   

     <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="row">
                  <div id="error_div" class="pull-right"></div>
                <div class="col-xs-12">
                    <div class="message-list-container">
                        <div class="message-list" id="students">
                            <table id="simple-table2" class="table  table-bordered table-hover"></table>
                        </div>
                    </div>
                </div>
            </div><!-- /.row -->
            <!-- /.modal-content -->
        </div>
    </div>
    <div class="row" id="SaveBtnDiv" style="display:none">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="row pull-right">
                <div class="col-xs-12">
                    <button id="SaveBtn" class="btn btn-sm btn-primary">
                                <i class="ace-icon fa fa-save"></i>
                                Save
                            </button>
                </div>
            </div><!-- /.row -->
            <!-- /.modal-content -->
        </div>
    </div>
    
    <!-- PAGE CONTENT ENDS -->
</div>
<!-- main.cont -->

@section PopupsAndTemplates
{
    @{
        Html.RenderAction("YesNoModal", "Partial");
    }
     <script id="StudentTemplate" type="text/x-handlebars-template">
    
        <thead>
            <tr id="thead">
            
                <th class="asterisk">Login</th>
                <th class="asterisk">Name</th>
                <th class="asterisk">Father Name</th>
                <th class="asterisk">Section</th>
                <th class="asterisk">Email</th>
               <th class="asterisk">IsOldCampus</th>             
            </tr>
        </thead>
        <tbody>
            {{#each StudentList}}
            <tr >
        
                <td contenteditable='true'>{{Login}}</td>
                <td contenteditable='true'>{{Name}}</td>
                <td contenteditable='true'>{{StdFatherName}}</td>
                <td contenteditable='true'>{{Section}}</td>
                <td contenteditable='true'>{{Email}}</td>               
                 <td  contenteditable='false' align="center" align="middle" id={{IsOldCampus}}   >
                     <input  type="checkbox"  {{#ifEqual IsOldCampus 1}}checked{{/ifEqual}} value="{{IsOldCampus}}"  />    
                </td>       
            </tr>
            {{/each}}
        </tbody>
    </script>
  
}

PRM/MainApplication/PUCIT.AIMRL.PRM.MainApp/Views/Security/GoogleUsers.cshtml
@{
    ViewBag.Title = "Index";
}
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Header
{
    <script type="text/javascript" src="@Url.Content("~/Scripts/mywebapp/Security/mywebapp.ui.googleusers.js")?s=@DateTime.UtcNow.Ticks"></script>
    @*@Scripts.Render("~/bundles/users")*@
}
<style type="text/css">
    .currentpage {
        display: block;
    }

    .page {
        display: none;
    }

    .navlinks a {
        margin: 5px;
    }

    .selectedpg {
        color: red;
        background-color: grey;
        padding: 5px;
    }
</style>

@section scripts
{
    <script type="text/javascript">

        $(document).ready(function () {
            MyWebApp.UI.GoogleUsers.readyMain();
        });
    </script>
}
@section BreadCrumb
{
    <li>
        <a href='@Url.Content("~/Security/")'>Security</a>
    </li>
    <li>
        <a href='@Url.Content("~/Security/GoogleUsers/")'>Users</a>
    </li>
}

<div class="page-content">
    <div class="page-header">
        <div class="main-content">
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-3">
                        <label class="lbl">Name/Email</label>
                        <input id="txtTextToSearch" type="text" class="input-sm form-control" placeholder="Type Name/Login/Email/Section">
                    </div>
                    <div class="col-sm-2">
                        <label class="lbl">User Created? </label>
                        <select id="cmbIsActiveSearch" class="input-sm form-control">
                            <option value="-1">Any</option>
                            <option value="1">Yes</option>
                            <option value="0" selected>No</option>
                        </select>
                    </div>
                    <div class="col-sm-1" style="padding-top:15px">
                        <a role="button" class="pull-right btn-new-mail" data-toggle="modal" id="search">
                            <span class="btn btn-purple no-border">
                                <i class="menu-icon fa fa-search"></i>
                                <span class="bigger-110">Search</span>
                            </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">

            <div class="row">
                <div class="col-sm-10">
                    <div class="col-sm-2">
                        Page Size: <select id="cmbPageSizeSearch">
                            <option value="10" selected>10</option>
                            <option value="20">20</option>
                            <option value="30">30</option>
                        </select>

                    </div>
                    <div class="col-sm-2">
                        <span id="spResultsFound"> </span>
                    </div>
                    <div class="col-sm-6">
                        <ul class="pagination pull-right no-margin"></ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="row">
                <div class="col-xs-12">
                    <div class="message-list-container">
                        <div class="message-list" id="Users">
                            <table id="simple-table" class="table  table-bordered table-hover"></table>
                        </div>
                    </div>
                </div>
            </div><!-- /.row -->
        </div>
    </div><!-- /.page-header -->
</div>


@section PopupsAndTemplates
{
    @{
        Html.RenderAction("YesNoModal", "Partial");
    }
    
    <div id="EditRolesModal" tabindex="-1" class="modal" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="primary bigger">
                        Roles Assignment
                        <button type="button" id="closeedit" class="close" data-dismiss="modal">×</button>
                    </h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-12 col-sm-11">
                            <div class="space-4"></div>
                            <div class="row">
                                <div id="draggable" style="max-height:250px;overflow-y:auto">
                                    <ol id="sortable1" style="list-style-type:none"></ol>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-sm" data-dismiss="modal" id="CancelPermModal">
                        <i class="ace-icon fa fa-times"></i>
                        Cancel
                    </button>
                    <button class="btn btn-sm btn-primary" id="SaveMappings">
                        <i class="ace-icon fa fa-check"></i>
                        Save
                    </button>
                </div>
            </div>
        </div>
    </div>

    <script id="UserTemplate" type="text/x-handlebars-template">
        <thead>
            <tr>
                <th class="center">#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Request On</th>
                <th>User ID</th>
                <th>Approved On</th>
                <th scope="col" width="5%">Create User</th>
            </tr>
        </thead>

        <tbody>
            {{#each UserList}}
            <tr id="{{Email}}">

                <td align="center" class="studentids" name="UserId1">{{ID}}</td>
                <td name="Name" id="Name" value="{{Name}}">{{Name}}</td>
                <td name="Email" id="Email">{{Email}}</td>
                <td name="Email" id="Email">{{EntryTimeOnStr}}</td>
                <td id="Email">{{UserId}}</td>
                <td id="Email">
                    {{#ifEqual IsUsed true }}
                        {{UserCreatedOnStr}}
                    {{/ifEqual }}
                </td>

                <td align="center" align="middle">
                    <div class="tblActions">
                        {{#ifEqual IsUsed false }}
                        <a role="button" data-toggle="modal" class="edit btn-xs btn-new-mail  btn btn-purple no-border lnkEditMapping" title="Click to edit" id="editMapping">
                            <i class="menu-icon fa fa-pencil-square-o "></i>
                            <span class="bigger-110"></span>
                        </a>
                        {{/ifEqual }}
                        {{#ifEqual IsUsed true }}
                        <a href="#" class="btn btn-xs btn-round">
                            <i class="ace-icon icon-lock"></i>
                        </a>
                        {{/ifEqual }}
                    </div>
                </td>
            </tr>
        </tbody>
        {{/each}}
    </script>
    <script id="RoleTemplate" type="text/x-handlebars-template">
        {{#each RoleList}}
        <li class="dd-handle nondrag" id="{{Id}}">
            <input type="radio" name="rolesData">
            {{Name}}
        </li>
        {{/each}}
    </script>

}

PRM/MainApplication/PUCIT.AIMRL.PRM.MainApp/Views/Security/Index.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section BreadCrumb
{
    <li>
        <a href='@Url.Content("~/Security/")'>Security</a>
    </li>
}